// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Accordion: typeof import('./src/components/home/base/Accordion.vue')['default']
    AdminTicket: typeof import('./src/components/support/AdminTicketInformation.vue')['default']
    AdminTicketInformation: typeof import('./src/components/support/AdminTicketInformation.vue')['default']
    Button: typeof import('./src/components/home/base/Button.vue')['default']
    BuyTradeImage: typeof import('./src/components/home/landing/BuyTradeImage.vue')['default']
    copy: typeof import('./src/components/panel/PanelInvestChart.vue')['default']
    CryptoStatistic: typeof import('./src/components/home/landing/CryptoStatistic.vue')['default']
    DarkMode: typeof import('./src/components/DarkMode.vue')['default']
    DataTable: typeof import('./src/components/DataTable.vue')['default']
    Exchange: typeof import('./src/components/home/landing/Exchange.vue')['default']
    Footer: typeof import('./src/components/home/base/Footer.vue')['default']
    LearningContent: typeof import('./src/components/learning/LearningContent.vue')['default']
    LearningContentVideo: typeof import('./src/components/learning/contetnt/LearningContentVideo.vue')['default']
    LearningStepper: typeof import('./src/components/learning/LearningStepper.vue')['default']
    LineChart: typeof import('./src/components/home/LineChart.vue')['default']
    ListItem: typeof import('./src/components/home/landing/ListItem.vue')['default']
    Modal: typeof import('./src/components/modal.vue')['default']
    Navbar: typeof import('./src/components/home/base/Navbar.vue')['default']
    NavigationDrawer: typeof import('./src/components/NavigationDrawer.vue')['default']
    NavLink: typeof import('./src/components/home/NavLink.vue')['default']
    OverviewBox: typeof import('./src/components/panel/OverviewBox.vue')['default']
    PageTitle: typeof import('./src/components/shared/pageTitle.vue')['default']
    PanelFullReports: typeof import('./src/components/panel/PanelFullReports.vue')['default']
    PanelInvestChart: typeof import('./src/components/panel/PanelInvestChart.vue')['default']
    PanelMarketingChart: typeof import('./src/components/panel/PanelMarketingChart.vue')['default']
    PanelMembersChart: typeof import('./src/components/panel/PanelMembersChart.vue')['default']
    PanelTicketsReports: typeof import('./src/components/panel/PanelTicketsReports.vue')['default']
    PanelTransactionChart: typeof import('./src/components/panel/PanelMembersChart.vue')['default']
    PanelTransactionsChart: typeof import('./src/components/panel/PanelTransactionsChart.vue')['default']
    PartnerImage: typeof import('./src/components/home/landing/PartnerImage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Section: typeof import('./src/components/home/base/Section.vue')['default']
    Step: typeof import('./src/components/home/landing/Step.vue')['default']
    TicketMessages: typeof import('./src/components/support/TicketMessages.vue')['default']
    TradingToolImage: typeof import('./src/components/home/landing/TradingToolImage.vue')['default']
    UserTicketInformation: typeof import('./src/components/support/UserTicketInformation.vue')['default']
  }
}
